### ISSUE TITLE
Support for password prompts

### ISSUE THREAD

**Issue by skullydazed** [clueboard/milc#1]
We should have a way to securely collect sensitive data from a user, such as passwords.

**Comment by Erovia** [comment]
After quickly checking it, `argparse` lacks the option to handle sensitive data and the cleanest solution is to define a password object and use it as a custom action.
https://gist.github.com/namnv609/f462c194e80ed4048cd2

How should we integrate it into MILC, tho?

As a new option when defining arguments like `@cli.argument(..., type = Password, ...)` or as `milc.questions.password`?
I'd prefer the former.

**Comment by skullydazed** [comment]
I've been working on this one.

The basic problem with passing passwords as arguments is that they're visible to tools like ps. POSIX doesn't give us a way to hide that, and while it's possible to do on Linux I'd rather not have a feature that is secure on some platforms but not others. Given this I think it's not a good idea for MILC to support this directly.

I've started by implementing `milc.questions.password`:

```python
def password(prompt='Enter password:', *args, confirm=False, confirm_prompt='Confirm password:', validate=None, **kwargs):
    """Securely receive a password from the user.

    | Argument | Description |
    |----------|-------------|
    | prompt | The prompt to present to the user. Can include ANSI and format strings like milc's `cli.echo()`. |
    | confirm | Prompt the user to type the password again and make sure they match. |
    | confirm_prompt | The prompt to present to the user. Can include ANSI and format strings like milc's `cli.echo()`. |
    | validate | This is an optional function that can be used to validate the password, EG to check complexity. It should return True or False and have the following signature:<br><br>`def function_name(answer):` |
    """
```
