### ISSUE TITLE
Setting log_file_fmt through config file

### ISSUE THREAD

**Issue by tissieres** [clueboard/milc#11]
Hi,
Thanks for your framework first!
It looks like that "general" options like `verbose` or `log_file_fmt` are always overidden by arguments in the `merge_args_into_config` function even if these arguments are not set when executing our script. Is it on purpose? I think it would be better to be able to set such variable in the config file as well and merge only arguments that are set on the command-line.

Cedric

**Comment by skullydazed** [comment]
Apologies the late reply, I get a lot of github email and missed this in the shuffle.

Is this still an issue for you? I've tried a bit to reproduce it and can't seem to- when I set `general.verbose=True` it correctly remembers the setting, and if I set it to False I can still override with -v. I think some of the work we've done in the last several months may have corrected it.

**Comment by tissieres** [comment]
Well, I'm currently running on my own fork. I'll try to update to the latest version and will reopen the issue if needed.
Cheers
