### ISSUE TITLE
Setting an app's Author, Title and Version?

### ISSUE THREAD

**Issue by workflowsguy** [clueboard/milc#14]
From the documentation

```
MILC uses appdirs to determine the configuration file location. You can set your application’s name and author by setting environment variables:

os.environ['MILC_APP_NAME'] = sys.argv[0]
os.environ['MILC_AUTHOR_NAME'] = sys.argv[0]
```

I do not get the point of this - seemingly incorrect - text and code sample. Why would I want to store this outside of my application instead of setting it as config values inside so that I can display or store them?

Also, how do I set the version info so that it is displayed when the `-V` option is passed to my script?

**Comment by skullydazed** [comment]
Apologies for not seeing this sooner, I get a lot of github mail and it's easy for these things to get lost in the shuffle.

> Why would I want to store this outside of my application instead of setting it as config values inside so that I can display or store them?

When I implemented that I found myself in a catch-22. I need that information at `from milc import cli` time which limits where it can be set. Using environment variables is a kludge, and if there's a better solution I've missed I'd happily change how that works.

I've also reworked that doc section to better convey what setting those options affects.

> Also, how do I set the version info so that it is displayed when the -V option is passed to my script?

I just spent a bit of time working on this, as of `b581060` you can set that by setting the `MILC_APP_VERSION` environment variable. A new 1.3.0 release will be published soon.
