### ISSUE TITLE
Add animated spinner and progress bars

### ISSUE THREAD

**Issue by skullydazed** [clueboard/milc#2]
It's nice to show something happening while things are processing in the background. We should support spinner animations and progress indicators.

**Comment by mskymoore** [comment]
@skullydazed I think [enlighten](https://pypi.org/project/enlighten/) is definitely the way to go on this one.  Will you assign this issue to me please?

**Comment by skullydazed** [comment]
@mskymoore Thanks for your interest in working on this! I don't assign issues out that way, but rest assured you would be the only one working on it right now. :)

Enlighten does seem like a good choice, but I haven't looking in depth at it. It only solves half the problem however, we also need spinners for when we want to show progress happening but don't have a determinate end.

**Comment by mskymoore** [comment]
@skullydazed I think the answer to spinners is [halo](https://github.com/ManrajGrover/halo) thoughts?

**Comment by skullydazed** [comment]
I like halo. At one point I had it in requirements.txt (but commented out.)
