### ISSUE TITLE
Write a tool to generate reference docs from docstrings

### ISSUE THREAD

**Issue by skullydazed** [clueboard/milc#4]
I can't find a docstring to markdown generator worth using. The most promising contender, https://github.com/NiklasRosenstein/pydoc-markdown, generates documents that are hard to understand. Should see about extending or rewriting it to create better output.

**Comment by mskymoore** [comment]
What do you think about [sphinx](https://www.sphinx-doc.org/en/master/)?

**Comment by skullydazed** [comment]
@mskymoore I've used sphinx for many years, and it's a great tool in many ways. But I've never been able to internalize RST the way I have markdown, and in talking to many other programmers I've heard the same story. There's a big push to add a bunch of fancy RST features to docstrings, then time goes on and you forget how to use those features because it's not a frequent enough activity to internalize. 

But I use markdown every day, in a lot of places. This means I don't have to dig up the reference just to write a docstring, I just write a docstring and move on with my work.

**Comment by mskymoore** [comment]
@skullydazed I wonder how difficult it would be to convert sphinx to use markdown.  I share the sentiment about rst.  Did you generate the current docs with pydoc-markdown? @skullydazed

**Comment by skullydazed** [comment]
When I looked into it the markdown stuff for sphinx is still about generating full HTML sites. What I want here is pretty narrowly focused- package docstrings into nice looking markdown documents. That way we can use any of a growing number of packages designed to render a pile of markdown as a nice site.

**Comment by skullydazed** [comment]
We have generated api docs now thanks to pydoc-markdown
